# NumPy Basics

python list:<br>
my_list = [12,13,14,15]

NumPy Arrays:<br>
import numpy as np<br>
my_array = np.array([12,13,14,15])

Both are ordered, mutable and contains duplicate. And supports indexing, slicing, iterating.

Difference:<br>
Lists are built in data structures of python whereas arrays must be imported from NumPy package or from array module.<br>
Lists can hold data of different data type whereas array can hold data of same data type only.<br>
Lists are flexible whereas once we difined dimension of array, we can not change it.<br>
Lists consume more memory whereas arrays consume less memory.<br>
Lists consume six times memory than of array.<br>
Lists saves object type, refereance count, object value, size whereas array saves only elements.<br>

In [70]:
# need to run a loop to multiply all elements of list.

number_list = [1, 2, 3, 4]

product = 1 
# Don't use 0 here, otherwise, you'll get zero.
for i in number_list:
    product = i * product
print('The product is',product)

The product is 24


In [ ]:
import numpy as np

In [72]:
# Here no loop required.
my_array = np.array([1,2,3,4])
product = my_array[0] * my_array[1] * my_array[2] * my_array[3]
print('The product is',product)

The product is 24


In [73]:
my_list21 = [111,222,333]
my_array21 = np.array([111,222,333])

In [78]:
import sys

In [79]:
# Get size of my_list21
sys.getsizeof(my_list21) * len(my_list21)

264

In [81]:
# Get size of my_array21
my_array21.itemsize * my_array21.size

24

It indicates the difference in memory consumption.

In [ ]:
import pandas as pd

In [1]:
print ('Hello World')

Hello World


In [4]:
myarray1 = np.array([1,2,3,4,5,6,7,8,9,10],np.int8)
print(myarray1)
myarray2 = np.array([200,500,1000],np.int32)
print(myarray2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 200  500 1000]


In [ ]:
myarray3 = np.array([10,20,11,21,23],np.int16)
myarray4 = np.array([123,223,214,233],np.int32)

In [ ]:
print(myarray3)

In [ ]:
myarray5 = np.array([900,2322,323],np.int32)
myarray6 = np.array([900,343,456],np.int32)

In [ ]:
myarray7 = np.array([[123,454,554]],np.int16)

In [ ]:
print(myarray7)

In [ ]:
print(myarray7[0,2])

In [ ]:
print(myarray7[0,0])

In [ ]:
myarray8 = np.array([[121,232],[432,455]],np.int16)

In [ ]:
print(myarray8)

In [ ]:
myarray8

In [ ]:
print(type(myarray8))

In [ ]:
myarray2[2]

In [ ]:
print(myarray2)

In [ ]:
myarray3 = np.array([[111,222,333,555]],np.int16)
print(myarray3)

In [ ]:
myarray3[0,1]

In [ ]:
myarray4 = np.array([[900,777,433,455]],np.int32)
myarray4
myarray4[0,2]

In [ ]:
myarray5 = np.array([[222,121,2332,121]],np.int32)
myarray5[0,2]

In [ ]:
myarray8.dtype

In [ ]:
print(type(myarray8))

In [ ]:
print('Hello')

In [ ]:
myarray8.dtype

In [ ]:
myarray8.shape

In [ ]:
myarray8.size

In [ ]:
floatarray1 = np.array([1.2,1.3,1.44],np.float16)

In [ ]:
floatarray1

In [ ]:
floatarray1.dtype

In [ ]:
floatarray1.shape

In [ ]:
floatarray1.size

##### Get info about created array

In [ ]:
myarray1.shape

In [ ]:
myarray3.shape

In [ ]:
myarray2.shape

In [ ]:
myarray5.shape

In [ ]:
myarray5.dtype

In [ ]:
myarray2.dtype

In [ ]:
myarray1.dtype

In [ ]:
myarray6 = np.array([[1.2,1.44,4.55]],np.float32)
myarray6
print(myarray6)
myarray6.shape
myarray6.dtype

In [ ]:
listarray1 = np.array([[1,2,3],[5,6,7],[8,9,10]])
print(listarray1)

In [ ]:
listarray2 = np.array([[33,44,55],[77,88,99]])
print(listarray2)

In [ ]:
listarray1.dtype

In [ ]:
print(listarray1)
listarray1.shape

In [ ]:
listarray3 = np.array([[100,200,300],[700,800,900]])
print(listarray3)

In [ ]:
listarray3.shape

In [ ]:
listarray3.dtype

In [ ]:
listarray3.size

In [ ]:
listarray1

##### Change element in array

In [ ]:
listarray1[0,0] =100

In [ ]:
print(listarray1)

##### Creation of array from list

In [ ]:
listarray4 = np.array([[232,332,322],[322,433,323]])
print(listarray4)

In [ ]:
listarray4

# Working with NumPy array

In [82]:
# create integer array

int_array = np.array([11,22,33,44,55,999])

# print

print(int_array)

[ 11  22  33  44  55 999]


In [83]:
# As indexing of elements starts from 0
# Let us check 0th element.

print(int_array[0])

11


In [85]:
# As array is mutable means objects whose values can be changed after they are created.
# Let us chanhe 0th element to 5555.

int_array[0] = 5555

# print

print(int_array)

[5555   22   33   44   55  999]


In [86]:
# Check data type of int_array

int_array.dtype

dtype('int64')

here int is data type and 64 is number of bytes that represent each element.

In [93]:
# Change dtype to 32

from numpy import int32


int_array_smaller = np.array(int_array, dtype=int32)

In [94]:
int_array_smaller.dtype

dtype('int32')

Get clear understanding of dtype for int, float, unsigned int, complex numbers.

In [100]:
# create array with specific dtype
from numpy import int8
# method 1
my_array22 = np.array([10,22,121,222], np.int32)

# method 2
my_array23 = np.array([23,22,3,44], dtype=int8)

In [ ]:
print(my_array22.dtype)
print(my_array23.dtype)

int32
int8


In [108]:
# Check total bytes consumed in memory
int_array.nbytes

48

In [109]:
# Check total bytes consumed in memory
int_array_smaller.nbytes

24

Memory consumption concept clearance is useful for machine learning algorithms.

# Multidimensional Arrays

1D array is Vector<br>2D array is Matrix<br>3D array is Tensor

In [111]:
my_array1_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [112]:
my_array1_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [114]:
print(my_array1_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [117]:
# It is 2D array, that's why to access element in 2D array, we need two indices.
my_array1_2d[0,0]

np.int64(1)

In [116]:
my_array1_2d[0,2]

np.int64(3)

In [121]:
# Let us check data type of my_array1_2d
my_array1_2d.dtype

dtype('int64')

In [119]:
print(my_array1_2d.dtype)

int64


In [123]:
# Let us check number of dimensions/
my_array1_2d.ndim

2

# Three Dimensional Array

In [125]:
# Array of two 2D array is 3D array.

my_array1_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [126]:
print(my_array1_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Create array from python data structures

In [127]:
list_abc = [989,34,5433,433]
list_abc

[989, 34, 5433, 433]

In [134]:
array_abc = np.array(list_abc)
print(array_abc)
print(array_abc.dtype)

[ 989   34 5433  433]
int64


In [135]:
list_pqr = [1,1000,1500,-1.223,-222.38,1000.6788]
list_pqr

[1, 1000, 1500, -1.223, -222.38, 1000.6788]

In [136]:
array_pqr = np.array(list_pqr)
array_pqr

array([ 1.0000000e+00,  1.0000000e+03,  1.5000000e+03, -1.2230000e+00,
       -2.2238000e+02,  1.0006788e+03])

In [137]:
array_pqr.dtype

dtype('float64')

Here list_pqr is converted into array and array type is converted into float as most general elements in list_pqr are float.

In [138]:
list_xyz = [100, 'Ram', 200, 300, 600]
list_xyz

[100, 'Ram', 200, 300, 600]

In [139]:
array_xyz = np.array(list_xyz)
print(array_xyz)

['100' 'Ram' '200' '300' '600']


In [ ]:
array_xyz

dtype('<U21')

Here dtype is unicode string.

In [149]:
# Create string array
my_array24 = np.array(['Ram', 'Shyam'],dtype='S')

# Create int array
my_array25 = np.array([1,2,3], dtype='i')

# Create float array
my_array25 = np.array([1.2, 1.3, 4.4, 6,9], dtype='f')

In [151]:
# Tuple is array which is immutable.
tuple1 = (12,122,121,121)

In [154]:
array_t1 = np.array(tuple1)
array_t1

array([ 12, 122, 121, 121])

In [155]:
array_t1.dtype

dtype('int64')

In [156]:
list_dim = [[12,12,11],[11,54,56],[77,76,89],[43,55,54]]

In [158]:
array_list_dim = np.array(list_dim)
array_list_dim

array([[12, 12, 11],
       [11, 54, 56],
       [77, 76, 89],
       [43, 55, 54]])

In [160]:
list_dim2 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
array_list_dim2 = np.array(list_dim2)
array_list_dim2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])